//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advert
    {
        public int id { get; set; }
        public string advert1 { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> advNo { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string url { get; set; }
    }
}
