//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> commentator_id { get; set; }
        public Nullable<int> newsfeed_id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual user user { get; set; }
        public virtual NewsFeed NewsFeed { get; set; }
    }
}
